version: '2'
services:

  web:
    image: joesweeny/cocktalesplatform_web:latest
    environment:
      DB_DSN: mysql:host=mysql;dbname=cocktales
      DB_USER: dev
      DB_PASS: password
      AWS_FILESYSTEM_ENABLED: 'false'