version: '2'
services:

  web:
    build:
      dockerfile: ./docker/web/Dockerfile
      context: ./
    volumes:
     - .:/opt

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ./
    ports:
     - "80"
    volumes:
     - .:/opt
    links:
     - web

  mysql:
    image: 'mysql:5.6'
    ports:
     - '3306:3306'
    volumes:
     - .:/opt
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=cocktales
     - MYSQL_USER=dev
     - MYSQL_PASSWORD=password
