version: 2
jobs:
  build:
    working_directory: ~/cocktalesplatform
    machine:
      image: circleci/classic:201711-01

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo add-apt-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install php7.1
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

      - run:
          name: Build Release Image
          command: |
            composer install --ignore-platform-reqs --no-dev --optimize-autoloader
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: |
            composer install --ignore-platform-reqs
            docker-compose -f docker-compose.yml run web bash /opt/bin/test

      - deploy:
           name: Deploy to Staging/Production
           command: |
             if [ "${CIRCLE_BRANCH}" == "feature/circle" ]; then
              curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
              python get-pip.py
              pip install awscli
              login="$(aws ecr get-login --no-include-email --region us-east-2)"
              ${login}
              docker tag "${DOCKER_IMAGE}:latest" "${ECR_ENDPOINT}/${DOCKER_IMAGE}:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/${DOCKER_IMAGE}:${CIRCLE_SHA1}"
             fi
