version: 2
jobs:
  build:
    working_directory: /opt
    docker:
      - image: joesweeny/php-awscli-docker-compose:v2

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Release Image
          command: |
            composer install --ignore-platform-reqs --no-dev --optimize-autoloader
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: |
            composer install --ignore-platform-reqs
            docker-compose -f docker-compose.yml run web /bin/bash /opt/bin/test

      - run:
          name: Teardown
          command: |
            docker-compose -f docker-compose.yml down -v
