version: 2
jobs:
  build:
    working_directory: /opt
    docker:
      - image: circleci/php:7.1.4-fpm-browsers

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Release Image
          command: |
#            composer install --ignore-platform-reqs --no-dev --optimize-autoloader
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: |
#            composer install --ignore-platform-reqs
            docker-compose -f docker-compose.yml run --entrypoint='/bin/sh' web /opt/bin/test

      - run:
          name: Teardown
          command: |
            docker-compose -f docker-compose.yml down -v
