version: 2
jobs:
  build:
    machine: true
      image: circleci/classic:201711-01

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
            curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
            php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
            php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --snapshot \
            rm -f /tmp/composer-setup.*

      - run:
          name: Build Release Image
          command: |
            composer install --ignore-platform-reqs --no-dev --optimize-autoloader
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: |
            composer install --ignore-platform-reqs
            docker-compose -f docker-compose.yml run web /opt/bin/test

      - run:
          name: Teardown
          command: |
            docker-compose -f docker-compose.yml down -v
