version: 2
jobs:
  build-and-test:
    working_directory: ~/cocktalesplatform
    machine:
      image: circleci/classic:201711-01

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo add-apt-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install php7.1
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

      - run:
          name: Build Release Image
          command: |
            composer install --ignore-platform-reqs --no-dev --optimize-autoloader
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: |
            composer install --ignore-platform-reqs
            docker-compose -f docker-compose.yml run web bash /opt/bin/test

  deploy-staging:
    working_directory: ~/cocktalesplatform
    machine:
      image: circleci/classic:201711-01

    steps:
      - run:
          name: Tag and push image
          commands: |
            docker images

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - staging-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: feature/circle
